export const LOADING_TEXTS = [
  'Crunching your financial vibes...',
  'Counting coins like a broke genie...',
  'Fetching your moolah realness...',
  'Chasing those paper trails...',
  'Summoning your transaction tea...',
  'Doing rich-people math...',
  'Checking under the couch cushions...',
  'Your money is on its way, hold tight...',
  'Polishing your profit margins...',
  'Scanning the financial matrix...',
  'Making your bank account look good...',
  'Whispering to the bank gnomes...',
  'Rocket science? Nah, just your expenses...',
  'Counting zeros like a pro...',
  'Gathering your financial glow-up...',
  'Your transactions are doing yoga... zen mode...',
  'Decoding adulting for you...',
  'Hot financials coming right up...',
  'The economy is watching, act cool...',
  'Brb, optimizing your cash flow...',

  'Pulling up your money trail...',
  'Sorting through the financial chaos...',
  'Tracking every penny for you...',
  'Finding where the money went...',
  'One transaction at a time...',
  'Untangling your expense history...',
  'Loading your spending story...',
  'Retrieving the cash chronicles...',
  'Piecing together your payment puzzle...',
  'Your transaction history is warming up...',
  'Gathering the receipts of life...',
  'Making sense of the money mess...',
  'Hunting down your latest transactions...',
  'Scrolling through your money timeline...',
  'Preparing your financial flashbacks...',
  'Cashing in on some loading time...',
  'Just a sec, your history is arriving...',
  'Reviewing the ledger of legends...',
  'Fetching the full money saga...',
  'Almost there, balancing the books...',
];

export const getRandomLoadingText = () =>
  LOADING_TEXTS[Math.floor(Math.random() * LOADING_TEXTS.length)];
