
auth.token=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

defaults.org=mak-0x
defaults.project=react-native

defaults.url=https://sentry.io/
